# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "72 79 4C 64 C5 DD 89 F6 F3 73 F7 99 25 E3 0C F8 02 8B 0B 7B"
      - run:
          name: connect with instance
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan 18-236-91-26 >> ~/.ssh/known_hosts
            else
                echo "No matching branch"
            fi 
            echo "Host *" >> ~/.ssh/config
            echo "    User ubuntu" >> ~/.ssh/config
            echo "    ForwardAgent Yes" >> ~/.ssh/config
      - run:
          name: create a new directory, file and add some text
          command: |
            mkdir new_directory
            cd new_directory
            touch new.txt
    branches:
      only:
      - master

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # # run tests!
      # # this example uses Django's built-in test-runner
      # # other common Python testing frameworks include pytest and nose
      # # https://pytest.org
      # # https://nose.readthedocs.io

      # - run:
      #     name: fetch latest code
      #     command: |
      #       git pull origin master

        
      # - run:
      #     name: run requirements
      #     commands: pip install -r requirements.txt